version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: flask_postgres_db
    restart: always
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: flask_api
    restart: always
    command: python run.py
    

    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://flaskuser:flaskpassword@db:5432/flaskdb
    depends_on:
      - db

volumes:
  postgres_data:
